apiVersion: apps/v1
kind: Deployment
metadata:
  name: My-hello-world
spec:
  selector:
    matchLabels:
      app: my-hello-world
  replicas: 2
  template:
      metadata:
    labels:
      app.kubernetes.io/name: my-hello-world
    spec:
      containers:
      - name: my-hello-world
        image: erikgjacobsen/my-hello-world:arm64
        ports:
        - containerPort: 8080
